import BackButton from "@/components/buttons/backButton"
import "./main.css"

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ flexGrow: 0 }}>
          <p>Header</p>
        </header>
        <div style={{ flexGrow: "1", padding: "12px 0" }}>{children}</div>
        <footer style={{ flexGrow: 0 }}>Footer</footer>
      </body>
    </html>
  )
}
